---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skate-hps
  labels:
    scale: horizaontal
spec:
  behavior:
    scaleUp:
      policies:
        - periodSeconds: 300
          type: Pods
          value: 2
  maxReplicas: 4
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skate

